#name: GitHub Actions Demo
#on:
#  push:
#
#jobs:
#  Explore-GitHub-Actions:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#      - name: List files in the repository
#        run: |
#          ls -al  ${{ github.workspace }}
#      - run: echo "This job's status is ${{ job.status }}."
#      - name: docker build
#        run: |
#          docker build -t weby_ufg .
#      - name: image upload to ECR
#        run: |
#          docker push


jobs:
  ci:
    name: "Integration"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout Code"
        uses: "actions/checkout@v2"

      - name: "Lint code"
        run: |
          echo "Linting repository"
      - name: "Run unit tests"
        run: |
          echo "Running unit tests"
  cd:
    name: "Deployment"
    runs-on: "ubuntu-latest"
    needs:
      - ci
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: "Checkout Code"
        uses: "actions/checkout@v2"

      - name: Set tag
        id: vars
        run: echo "::set-output name=tag::${GITHUB_REF#refs/*/}"
      - name: Configure AWS credentials
          uses: aws-actions/configure-aws-credentials@v1
          with:
            aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: ${{ secrets.AWS_REGION }}
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1