#name: GitHub Actions Demo
#on:
#  push:
#
#jobs:
#  Explore-GitHub-Actions:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#      - name: List files in the repository
#        run: |
#          ls -al  ${{ github.workspace }}
#      - run: echo "This job's status is ${{ job.status }}."
#      - name: docker build
#        run: |
#          docker build -t weby_ufg .
#      - name: image upload to ECR
#        run: |
#          docker push


name: "workflow"

'on':
  push:
    branches:
      - main
    tags:
      - "*"
  pull_request:
    branches:
      - main

jobs:
  integration:
    name: "CI"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout Code"
        uses: "actions/checkout@v2"

      - name: "Lint code"
        run: echo "Linting repository"

      - name: "Run unit tests"
        run: echo "Running unit tests"
      cd:
        name: "Deployment"
        runs-on: "ubuntu-latest"
        needs:
          - ci
        if: startsWith(github.ref, 'refs/tags/')