name: GitHub Actions Demo
on:
  push:
    paths:
    - 'config/**' 
    - '.github/workflows/*'
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: List files in the repository
        run: |
          ls -al  ${{ github.workspace }}
      - run: echo "🍏 This job's status is ${{ job.status }}."
      - name: docker build
        run: |
          ls -al 
